# netlify.toml — конфиг сборки и хостинга

[build]
  # Команда сборки Astro
  command = "npm run build"
  # Папка, которую публикует Netlify
  publish = "dist"

###########################################################
# РЕДИРЕКТЫ
###########################################################
# Любой запрос, пришедший на apex-домен (wajciukmedia.pl),
# уводим 301 на канонический https://www.wajciukmedia.pl/…
# Работает и для http, и для https. Восклицательный знак
# НЕ ИСПОЛЬЗУЕМ — он только для файла `_redirects`.
[[redirects]]
  from = "/*"
  to = "https://www.wajciukmedia.pl/:splat"
  status = 301
  force  = true
  conditions = { Host = ["wajciukmedia.pl"] }

###########################################################
# ЗАГОЛОВКИ БЕЗОПАСНОСТИ (необязательно, но полезно)
###########################################################
#[[headers]]
# for = "/*"
#  [headers.values]
#    # Включаем HSTS — принудительный HTTPS в браузере
#    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
#    X-Content-Type-Options    = "nosniff"
#   X-Frame-Options           = "SAMEORIGIN"
#    Referrer-Policy           = "no-referrer-when-downgrade"
    # Принудительно апгрейдим любые http-ресурсы до https
#    Content-Security-Policy   = "upgrade-insecure-requests"